# .github/release.yml

changelog:
  exclude:
    labels:
      - Release/Ignore
      - Type/Duplicate
      - Type/WontFix
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🔥
      labels:
        - Release/Breaking
    - title: Exciting New Features 🎉
      labels:
        - Type/Enhancement
    - title: Bug Fixes 🪲
      labels:
        - Type/Bug
    - title: Documentation Updates 📄
      labels:
        - Type/Documentation 
    - title: Project Maintenance 🔧
      labels:
        - Type/Documentation 
    - title: Other Changes
      labels:
        - "*"