##### 
# Core Site Settings
#####

baseURL: "localhost:1313" # BaseURL of the website, used in RSS feeds and site rendering
buildFuture: true         # Include content with publishdate in the future
enableRobotsTXT: true     # Generate a customized robots.txt
title: "Hugo Creator Theme" # Title of the website

##### 
# Menu Display
##### 
menu: # Main Menu
  # Main Menu (Top Navigation)
  main:
    - name: "Home"
      weight: 1
      url: "/"
    - name: "About"
      weight: 2
      url: "/about"
    - name: "Episodes"
      identifier: "episodes"
      weight: 3
      url: "#"
    - name: "Past"
      url: "/episode"
      weight: 1
      parent: "episodes"
    - name: "Upcoming"
      url: "/upcoming"
      weight: 2
      parent: "episodes"
    - name: "Blog"
      weight: 4
      url: "/Blog"
    - name: "Speaking"
      identifier: "speaking"
      weight: 5
      url: "#"
    - name: "Talks"
      url: "/talk"
      weight: 1
      parent: "speaking"
    - name: "Presentations"
      url: "/presentation"
      weight: 2
      parent: "speaking"
    - name: "People"
      weight: 6
      url: "/person"
    - name: "Series"
      weight: 7
      url: "/series"
  # Footer Menu (Bottom Navigation)
  footer:
    - name: "Get Involved"
      weight: 1
      url: "#"
    - name: "Code of Conduct"
      weight: 1
      url: "/code-of-conduct"
    - name: "Privacy"
      weight: 2
      url: "/privacy-policy"
    - name: "Cookies"
      weight: 3
      url: "/cookie-policy"

module:
  imports:
    path: "github.com/cloudwithchris/hugo-creator"
  mounts:
    - source: "node_modules/bootstrap/dist/js"
      target: "assets/js"
    - source: "node_modules/@popperjs/core/dist/umd"
      target: "assets/js"
    - source: "node_modules/jquery/dist"
      target: "assets/js"
    - source: "node_modules/fuse.js/dist"
      target: "assets/js"
    - source: "node_modules/bootstrap/scss"
      target: "assets/sass/bootstrap"
    - source: "./node_modules/@fortawesome/fontawesome-free/scss"
      target: "assets/sass/fontawesome"
    - source: "./node_modules/@fortawesome/fontawesome-free/webfonts"
      target: "static/webfonts"
    - source: "assets"
      target: "assets"
    - source: "static"
      target: "static"

# This enables the search functionality
# to work, as it searches over the json file.
# In effect, this allows the layouts/index.json
# file to be rendered.
outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"

# Custom Parameters that drive the site's
# configuration. This includes custom
# functionality, such as comments,
# RSS feed options, etc.
params:
  # Parameters relating to site content
  content:
    # Links to channels for the platform. This will be
    # for the site itself, rather than a specific user.
    channels:
      apple: "https://podcasts.apple.com/gb/podcast/cloud-with-chris/id1499633784"
      google: "https://podcasts.google.com/feed/aHR0cHM6Ly93d3cuY2xvdWR3aXRoY2hyaXMuY29tL2VwaXNvZGUvaW5kZXgueG1s?sa=X&ved=0CAMQ4aUDahcKEwiwsr2N1ePtAhUAAAAAHQAAAAAQBA"
      spotify: "https://open.spotify.com/show/3oBrdKm5grzl58GBiV0j2y"
    # Configuration information related to the RSS feed.
    # Several of these options will drive the metadata used
    # by external feeds for Podcasts, for example, Apple Podcasts.
    #
    # Note: Do not use markdown in these fields, as they are rendered
    # in an RSS feed.
    feed:
      explicit: "no" # This is set to either yes or no.
      itunes_author: "Chris Reddington"
      itunes_image: "https://www.cloudwithchris.com/img/cloudwithchrislogo.png" # This should be an absolute URL.
      itunes_subtitle: "Exploring Cloud concepts with Chris Reddington!"
      itunes_summary: "Exploring Cloud concepts with Chris Reddington (Welsh Tech Geek, Cloud Advocate, Musical Theatre Enthusiast and Improving Improviser!). We will regularly invite guests to talk about their experiences with the cloud and hear about some of the lessons learned around their cloud journey."
      itunes_owner_name: "Chris Reddington"
      itunes_owner_email: "chris@cloudwithchris.com" # Contains the e-mail address that will be used to contact the owner about their Podcast on iTunes.
      itunes_top_category: "Technology" # https://podcasters.apple.com/support/1691-apple-podcasts-categories
      itunes_first_sub_category: "Podcasting"
      itunes_second_sub_category: "Software How-To"
      language: "en-gb"
    # Configuration information for the site itself. Some of 
    # this will also be used within RSS feeds, etc.
    site:
      author: "Chris Reddington" # Owner of the site
      copyright:
        additional_information: "[Hugo Creator](https://github.com/cloudwithchris/Hugo-Creator) theme created by [Chris Reddington](https://www.cloudwithchris.com)" # I'd greatly appreciate if you would keep this in!
        established: "2020" # Year established (i.e. start year in a range)
        notice: "[Chris Reddington](https://www.christianreddington.co.uk). Proudly running using [Hugo](https://gohugo.io/)." # Your Copyright
      description: "This is my wonderful site description" # This is used in site metadata and RSS feeds.
      #####
      # Keywords
      #####
      #
      # Keywords are used for site metadata tags.
      # These are concatenated with tags from pages.
      #
      keywords:
        - list
        - your
        - keywords
        - here
      language_name: "English"
      logo: "/img/Cloud.png" # Relative path to the site's logo
      media_prefix: "https://podcasts.cloudwithchris.com/" # Media_Prefix is used when referencing podcast audio files. The media files in individual episodes will be concatenated after the media_prefix above.
      ogimage: "/img/cloudwithchrislogo.png" # Used within RSS feeds.
    social:
      discord: "9FJctHP9Zv"
      facebook: "CloudWithChris"
      github: "CloudWithChris"
      linkedin: "chrisreddington"
      tiktok: "cloudwithchris"
      twitter: "CloudWithChris"
      twitter_domain: "cloudwithchris.com" # This domain shows in twitter cards as "View on `twitter_domain`"
      youtube: "CloudWithChris"
    theme:
      accentcolor: "#157DB9"
      complimentcolor: "#CFDCE1"
      footercolor: "#157DB9"
      mainlinkcolor: "#0C62A8"
  # Parameters relating to site features and functionality
  features:
    # Settings related to the Social bar at top of site
    socialbox: true
  # Settings relating to site security. This mainly
  # comprises of Content Security Policies.
  security:
    # If all CSP properties are empty strings, then
    # the CSP section will not be rendered. If at least 1
    # contains a string, then it will be rendered.
    csp:
      scriptsrc: ""
      imgsrc: ""
      connectsrc: ""
      framesrc: ""
      objectsrc: ""
# Taxonomies in hugo are used to easily identify content that belongs
# to a given piece of metadata. This is particularly useful for tags,
# or pieces of content that appear in a series. All taxonomies used within
# the theme are configured below.
taxonomies:
  tag: "tags"
  series: "series"